### ISSUE TITLE
EBS Usage is zero

### ISSUE THREAD

**Issue by salehkhazaei** [kaytu-io/kaytu#65] opened 2024-05-08 12:33 UTC
![image](https://github.com/kaytu-io/kaytu/assets/9839920/a093f192-0ab9-493d-99e3-bb727e61f39f)

**Comment by Mahanmmi** [comment] 2024-05-08 13:37
It was caused by sending metrics with non-hashed volume id key to the back-end, hence it not being able to map them to the resource.
Got fixed in the plugin

**Closed by Mahanmmi** 2024-05-08 13:37 UTC
